In [10]:
import tensorflow as tf
import numpy as np

In [33]:
def add_layer(inputs, in_size, out_size, activation_function=None):
    weights = tf.Variable(tf.random_normal([in_size, out_size]))
    biases = tf.Variable(tf.zeros([1, out_size]) + 0.1)
    sum = tf.matmul(inputs, weights) + biases
    if activation_function is None:
        outputs = sum
    else:
        outputs = activation_function(sum)
    return outputs

In [6]:
x_data = np.linspace(-1, 1, 300)[:, np.newaxis]
x_data

array([[-1.        ],
       [-0.99331104],
       [-0.98662207],
       [-0.97993311],
       [-0.97324415],
       [-0.96655518],
       [-0.95986622],
       [-0.95317726],
       [-0.94648829],
       [-0.93979933],
       [-0.93311037],
       [-0.9264214 ],
       [-0.91973244],
       [-0.91304348],
       [-0.90635452],
       [-0.89966555],
       [-0.89297659],
       [-0.88628763],
       [-0.87959866],
       [-0.8729097 ],
       [-0.86622074],
       [-0.85953177],
       [-0.85284281],
       [-0.84615385],
       [-0.83946488],
       [-0.83277592],
       [-0.82608696],
       [-0.81939799],
       [-0.81270903],
       [-0.80602007],
       [-0.7993311 ],
       [-0.79264214],
       [-0.78595318],
       [-0.77926421],
       [-0.77257525],
       [-0.76588629],
       [-0.75919732],
       [-0.75250836],
       [-0.7458194 ],
       [-0.73913043],
       [-0.73244147],
       [-0.72575251],
       [-0.71906355],
       [-0.71237458],
       [-0.70568562],
       [-0

In [7]:
#np.random.normal(loc = 0.0, scala = 1.0, size = None)
noise = np.random.normal(0, 0.05, x_data.shape)
noise

array([[  7.20332301e-02],
       [ -5.36542164e-02],
       [  4.43785390e-02],
       [ -3.84886438e-02],
       [  1.17087030e-02],
       [ -9.32173103e-03],
       [  5.77383041e-02],
       [  7.44792291e-02],
       [ -2.17038906e-02],
       [  8.45957008e-02],
       [ -9.06586178e-04],
       [  1.23111142e-02],
       [ -7.72478748e-02],
       [ -9.73778376e-02],
       [  4.19362642e-02],
       [ -3.47061724e-02],
       [ -4.64176654e-03],
       [  3.29157555e-02],
       [ -6.89915851e-03],
       [ -5.49507749e-03],
       [ -3.87763971e-02],
       [  5.91060122e-03],
       [  2.31325847e-02],
       [ -8.03454390e-02],
       [ -5.71354772e-02],
       [ -1.94021940e-03],
       [ -8.69775775e-02],
       [ -3.01056677e-02],
       [ -2.70251087e-02],
       [ -4.93391837e-02],
       [  4.37121496e-02],
       [ -1.01026747e-02],
       [ -6.57898425e-02],
       [ -9.85493861e-03],
       [ -1.07938772e-01],
       [  7.54655239e-02],
       [ -1.10547830e-01],
 

In [8]:
y_data = np.square(x_data) - 0.5 + noise
y_data

array([[ 0.57203323],
       [ 0.4330126 ],
       [ 0.51780166],
       [ 0.42178026],
       [ 0.45891287],
       [ 0.42490719],
       [ 0.47908147],
       [ 0.48302611],
       [ 0.3741362 ],
       [ 0.46781848],
       [ 0.36978837],
       [ 0.37056773],
       [ 0.26865989],
       [ 0.23627056],
       [ 0.36341477],
       [ 0.27469193],
       [ 0.29276542],
       [ 0.31842151],
       [ 0.26679465],
       [ 0.25647627],
       [ 0.21156197],
       [ 0.24470547],
       [ 0.25047344],
       [ 0.13563089],
       [ 0.14756581],
       [ 0.19157551],
       [ 0.09544208],
       [ 0.1413074 ],
       [ 0.13347086],
       [ 0.10032916],
       [ 0.18264236],
       [ 0.11817889],
       [ 0.05193255],
       [ 0.09739778],
       [-0.01106625],
       [ 0.16204733],
       [-0.03416725],
       [-0.0144888 ],
       [ 0.05542381],
       [ 0.00509497],
       [ 0.0830745 ],
       [ 0.05515481],
       [-0.08776276],
       [ 0.00802778],
       [ 0.05876414],
       [-0

In [13]:
xs = tf.placeholder(tf.float32, [None, 1])
ys = tf.placeholder(tf.float32, [None, 1])
xs

<tf.Tensor 'Placeholder_2:0' shape=(?, 1) dtype=float32>

In [34]:
l1 = add_layer(xs, 1, 10, activation_function=tf.nn.relu)
l1

<tf.Tensor 'Relu_4:0' shape=(?, 10) dtype=float32>

In [35]:
prediction = add_layer(l1, 10, 1, activation_function = None)
prediction

<tf.Tensor 'add_14:0' shape=(?, 1) dtype=float32>

In [37]:
loss = tf.reduce_mean(tf.reduce_sum(tf.square(ys - prediction), reduction_indices=[1]))

In [38]:
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(loss)

In [39]:
init = tf.initialize_all_variables()

In [40]:
sess = tf.Session()

In [41]:
sess.run(init)

In [42]:
for step in range(1000):
    sess.run(train_step, feed_dict = {xs: x_data, ys: y_data})
    if step % 50 == 0:
        print sess.run(loss, feed_dict = {xs: x_data, ys:y_data})

2.70853
0.00495029
0.00410497
0.00386716
0.00373783
0.00363765
0.00356587
0.00349961
0.00341264
0.0033546
0.00330817
0.003261
0.00321758
0.00316271
0.00311409
0.00308059
0.00306048
0.00304592
0.00303035
0.00301584
